#Add-Type -AssemblyName System.Windows.Forms
#Add-Type -AssemblyName System.Drawing

try {
    Add-Type -AssemblyName System.Windows.Forms -ErrorAction Stop
} catch { }

try {
    Add-Type -AssemblyName System.Drawing -ErrorAction Stop
} catch { }


[System.Windows.Forms.Application]::EnableVisualStyles()
Add-Type -TypeDefinition @"
using System.Runtime.InteropServices;
public class DPI {
    [DllImport("user32.dll")] public static extern bool SetProcessDPIAware();
}
"@
[DPI]::SetProcessDPIAware() | Out-Null

$ScriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Definition

# Logo 36x36 BMP (sin transparencia, GDI+ compatible)
$logoSmallB64 = "Qk1mDwAAAAAAADYAAAAoAAAAJAAAACQAAAABABgAAAAAADAPAADEDgAAxA4AAAAAAAAAAAAAAAAAAAAAAAAAAQIBAQIBAQIBAQIBAQIBAQIBAQIBAQIBAQIBAQIBAQIBAQIBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAQIBAQIBAQIBAQIBAQIBAQIBAQIBAQIBAQIBAQIBAQIBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADB0VDyYaDyQZDyQZDyQZDyQZDyQZDyQZDyQZDyQZDyQZDyYaDBwUAAAAAAAAAAAAAAAAAAAAAAAADB0UDyYaDyQZDyQZDyQZDyQZDyQZDyQZDyQZDyQZDyQZAwYEAAAAAAAAAAAAAAAAAAAAOZpqRseHQ72BRL+CRL+CRL+CRL+CRL+CRL+CRL+CQ72BR8iINZRmAAAAAAEBAAAAAAAAAAEAAAAAN5lpR8eHQ72BRL+CRL+CRL+CRL+CRL+CRL+CRL+CRcCDDCAWAAAAAQIBAAAAAAAAAAAAN5hoRMSFQbp/Qbt/Qbl+Qbl+Qbl+Qbl+Qbl+Qbl+QLd9RMGEM49iAAAAAAEBAAAAAAAAAAEAAAAANZRlRMCDQLd9Qbl+Qbl+Qbl+Qbl+Qbp+QryAQryAQ72BDB8WAAAAAQIBAAAAAAAAAAAAN5hoRMSFQbl+Q7+CR8mJR8qJR8qKR8mJR8mJR8qJRsiJStOQOJxrAAEBAAICAAEAAAAAAAIAAAEAOqJuStGORceIR8mJR8qJR8mJR8mJRcOFQrt/QryAQ72BDB8WAAAAAQIBAAAAAAAAAAAAN5hoRMOFQ7+CO6VxJ21LJmpIJWhHJmxKJ25LJmpIJWdHKHJOH1U7AAAAAAAAAAAAAAAAAAAAAAAAIFg8KXJOJ21LJ2xKJmxKJ2xKJ2xKMo5hRMGEQrt/Q72BDB8WAAAAAQIBAAAAAAAAAAAAN5hoRMGERcaHL4JZAAAABAcFBAgGAAAAAAAAAgIBAwYFAAAAAAAABxEMCRYPBQsIAwgGAwcFAwcFAAAAAAAAAAAAAAAAAAAAAAAAAAAAGUQvRsqKQbl+Q72BDB8WAAAAAQIBAAAAAAAAAAAAN5hoRMGERcaHL4RbAwYEPKt1RsaHFDQkAwcFPap0RsaHIVo+AQMCOJlpR8uKJF9BFTUlQLR7Pq94KnNPAAEADiQYPat1Pa12PKZyBQ0JG0s0R8mJQbl+Q72BDB8WAAAAAQIBAAAAAAAAAAAAN5hoRMGERcaHL4NaAgMCPbB4Sc2MESseDykcRseHRceHM45hAAAAOJ5sStOPKG5LAQEBOqJvRsqJRMCCCBINJ2tJSMyLR8yLJ2pJAAAAHVA3R8mJQbl+Q72BDB8WAAAAAQIBAAAAAAAAAAAAN5hoRMGERcaHL4NaAgMCPa13SMuKECYbIVs+R8uKQryAP7F4Bg4KNZZmSdCOKXBNAAAAFDUlRcKFRMOEMIRaO6ZyRcSFPat1Bg0KAAAAHE42RsmJQbl+Q72BDB8WAAAAAQIBAAAAAAAAAAAAN5hoRMGERcaHL4NaAgMCPa53R8mJEy8hMoxfRcWGP7J5RcaHFDQkMo5hStOPKG5LAAAAAAAAL4FYRcWGQ7+CQbt/R8mJH1I5AAAAAAAAHE01RsmJQbl+Q72BDB8WAAAAAQIBAAAAAAAAAAAAN5hoRMGERcaHL4NaAgMCPrB4RMKEHEkyP7F5P7J5J2lISdCOJGJDMYpfStSQKG5LAAAAAAEBDyYbRMKEQLd9Q8CDOqNvAgMCAQMCAAAAHE01RsmJQbl+Q72BDB8WAAAAAQIBAAAAAAAAAAAAN5hoRMGERcaHL4NaAgMCPrF5Qrt/KnNPRcaHNploDR4VRsaHNJFjNJFjSdKPKG5LAAAAAAAAJmdHRcaHQr2BQ8CDQbd9DSIXAAEAAAAAHEw0RcaHQLZ8Qrp/DB4WAAAAAQIBAAAAAAAAAAAANpdnQ7+DRMSGLoJZAgMCPq94Qbp/OqNvR8mJK3lTAAAAOqRwQbh9PKdyR8qKKW9MAAAADB0UQrl+RMOFOJtqOJ5sSM2LMYhdAAAAAAAAHlI5S9eSRcaHR8qKDSEXAAAAAQIBAAAAAAAAAAAAOp9tSMqKSc+NMoleAgMCQbh9R8mIRcKEStGOH1M5AQEBLHlTSdGOQ7+CSdGOK3VQAAAAMoldSc6MSs+NFTgnG0kySdGOSMyLGkUwAAAAEjEiK3lTJ3BMKXJOBxMNAAAAAQEBAAAAAAAAAAAAESodFTUlFTcmDiQZAwcFMI1hM5pqMpVnNJtrCR8XAAAAGDwpP6dyN5dnPKdyIFU7BxMONJxrM5pqMIlfAgMCBQwJNZJkOqNvL4FYAgQDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAsFFQ8HFA4GFA4GFQ8GDwsFAAAAAAAAAAAAAgAAAAAACwoGFhAHFg8HCwYCAAAAAAAAAAAAAAAAAQEBAQEBAQEBAgQCAgMCAgMCAAEAAAAAAAAAAAAAAAAAAAAAAQQDAgUDAwYDAQMCDAkExZo93q1D2KhC16hB1qdB0qM/uI84cFcjDQoFAAAAAAAAiWoq5bJF4a9EpIAyAAAAAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAwF2KhB7LhG5rNF8btH+cFK9b5I7blG98FKyp09Jx4NAAAAnHkv9L5J8LtHto02BAMBBAQBAwIBAQEAAAAAAAAABAMBCQcDCAYDCAYDAQEBAAAAAAAAAAAAAAAAAAAAECseFDYmFTgmDSUaDggE06VA57NE7LhGp4IzblYiqIIz6bVG365C9L5Iwpc7AgIBlXQt8btI7bhGroc0AAAAAAAAAAAAAAAABQQBAAAAVkMb26pCyp08zZ8+IRkKAAAAAgIBAAAAAAAAAAAAOp9tR8qKSc+NLolfDAIA1adB5rNE9b9JYkweAAAAAAAAaVIh8LtI3qxC98BKPC4TiGop9r9J57NEz6E+aVEgW0ccNyoRAAABAAAAAAAAYk0e+8NL6LVF67dGJh0LAAAAAgIBAAAAAAAAAAAANpZnQ7+DRcSFK4JaDAIA1adB5rNE9L5JbFMgBAMBAwIBBQMC0KI/5rNE98BJb1Yihmgp98BJ4a5D6bVF+MFK871I7blHvpQ6LCIPAAAAYkwe871J4a9D5LFEJRwLAAAAAgIBAAAAAAAAAAAAN5hoRMGERsaGLINbDAIA1adB5rNE9L5JalIgAAAABAQBAQEAvZM567ZF9r9Jel8miGkp98BJ4q9D5LFE2KhB6bVF47FD9sBJyJs9AQEBX0od9b9J4rBD5bJEJRwLAAAAAgIBAAAAAAAAAAAAN5hoRMGERsaGLINbDAIA1adB5rNE9L5Ja1MgAwIBAAAACggE16dB5bJE98BKalIhhmgp9b5J7bhGsYo2GhQJWUUc5rNF4a9D8btIIxsMVUIa98BJ4rBD5bJEJRwLAAAAAgIBAAAAAAAAAAAAN5hoRMGERsaGLINbDAIA1adB5rNE9b9JZU4fAAAACAYDhWcp8LtI3qxC9sBJMygRimsq871I8LtHn3wwAAAADAkF3axC5bFE8rxINysRU0AZ+MBK4rBD5bJEJRwLAAAAAgIBAAAAAAAAAAAAN5hoRMGERsaGLINbDAIA06ZB5rNE6LRFvpQ5mXcuxpo87LdG361C+MFJt444AAAAlnQt8btH5bJEzZ89fGEmt44457RF4a9D8bxIGhQJV0Qb98BJ4rBD5bJEJRwLAAAAAgIBAAAAAAAAAAAAN5hoRMGERsaGLINbDQIA3a1D8LtH6rVG871I+sJK9b5I8LtH9r9JuZA4HRYJAAAAnnow/cRK6LRF8LpH/MRL98BJ8LtH+8NLkXEtAAAAYkwe9b5J4rBD5bJEJRwLAAAAAgIBAAAAAAAAAAAAN5hoRMGERsaGLoVcCQMCs445y58+yJ0+yJw9xZk7upA4mncvVEEaAwIBAAAAAwIBg2Uo0qM/x5o7y549x5o8vpM6o34yWEQbBQQCAwIBYk0e9b5J4rBD5bJEJRwLAAAAAgIBAAAAAAAAAAAAN5hoRMGERcaGL4NaAAAAAAAAAQAAAgAABgMBBQQCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWUUb9r9J4rBD5bJEJRwLAAAAAgIBAAAAAAAAAAAAN5hoRMOFQr2BPat1L4FZL4JZLoJZLn9YBhEMAAAAAQEBAwIBBgUCAQAAUT4arYU1nXoxoHwxn3wxn3sxn3sxoX0xo38ypH8yon4yn3wxvpM66bZF5LFE5bJEJRwLAAAAAgIBAAAAAAAAAAAAN5hoRMSFQbl+Q7+CRseHRseHRsiHRsWGDB0UAQAAAQEBAAAABAMBAAAAeV4l/8pN7rlH8rxI8rxI8rxI8rxI8rxI8rxI8rxI8bxI8rxI7LdG47FE5LJE5LFEJRwLAAAAAgIBAAAAAAAAAAAAN5ppRcaGQryAQr2BQruAQruAQryAQrl/CxsTAAAAAQEBAAAABAMBAAAAc1kj9r9J4a9D5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5rNE6LRF6LRF6LRFJRwLAAAAAgIBAAAAAAAAAAAANpNlQ76BQLR7QbZ8QbZ8QbZ8Qbd8QbR7CxoSAAAAAQEBAAAABAMBAAAAb1Yi7bhH2ahB3atC3atC3atC3atC3atC3atC3atC3atC3atC3atC3atC3atC3KtCJBsLAAAAAgIBAAAAAAAAAAAABxALCBUOCBMOCBQOCBQOCBQOCBQOCBQOAgMCAAAAAAAAAAAAAAAAAAAADAkEGRMIFhEIFxEIFxEIFxEIFxEIFxEIFxEIFxEIFxEIFxEIFxEIFxEIFxEIFxEIBAMCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
$logoIconB64  = "Qk02MAAAAAAAADYAAAAoAAAAQAAAAEAAAAABABgAAAAAAAAwAADEDgAAxA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEBAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEBAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwQDBwoIBgoHBgoHBgoIBgoIBgoIBgoIBgoIBgoIBgoIBgoIBgoIBgoHBgoHBgoHBgoHBgoHBgoHBgoIBgoHBgoIBwoIAgIBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQYEBwoIBgkHBgoIBgoIBgoIBgoIBgoIBgoIBgoIBgoIBgoHBgoHBgoHBgoHBgoHBgoHBgoHBgoIBgkHAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAGj8sQrZ9Pql0Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqp2Pq13PqZzCRQPAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAJWJEQ7d+Pql0Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqt2Pqp1QLF5OJZoAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEYxR8yLQr2BQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ7+DQ8KEQrqACRYQAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAJ21MSM2MQr2BQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ8CDQ7+CRcaHPKhzAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRseHQbh9Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrp/Qr2AQbV8CRYQAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAJ2pKR8iIQbh9Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrt/Qrp+RMGDO6NwAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQryAQryAQryAQryAQryAQryAQryAQryAQryAQryAQryAQryAQryAQryAQryAQryAQruAQr6BQbZ9CRYQAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAJ2tKR8mJQbl+QryAQryAQryAQryAQryAQryAQryAQryAQryAQryAQryAQryAQryAQryAQrt/RMKEO6RxAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQryAQryAQryAQbp+Qbp+Qbp+Qbp+Qbp+Qbp+Qbp+Qbp+Qbp+Qbp+Qbp+Qbp+Qbp+Qbl+Qbx/QLR7CRYQAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAJ2pJRsaHQLd8Qbp+Qbp+Qbp+Qbp+Qbp+Qbp+Qbp+Qbp+Qbp+Qbl+Qrt/QryAQryAQryAQrt/RMKEO6RxAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQryAQryAQr2BRceHRseIRseIRseIRseIRseIRseIRseIRseIRseIRseIRseIRseIRsaIRsmJRcGECRcRAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAKXFOS9WRRcSFRseIRseIRseIRseIRseIRseIRseIRseIRseHRseIRMOFQruAQryAQryAQrt/RMKEO6RxAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQryAQr2BQLZ8MIVbL4NaL4NaL4NaL4NaL4NaL4NaL4NaL4NaL4NaL4NaL4NaL4NaL4JaL4RaL39YCBALAAAAAQEBAAAAAAAAAAAAAAAAAAAAAAAAAQIBAAAAHUs0M4xgLoFYL4NaL4NaL4NaL4NaL4NaL4NaL4NaL4NaMIRaL4JZN5ppQ8CDQrt/QryAQrt/RMKEO6RxAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKhzAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAQICAQICAQICAQICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGUQwRsmJQbl+QryAQrt/RMKEO6RxAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBQkGAQIBAgQDAgMDAgMDAgMDAgMCAQICAQIBAQEAAgICAQEBAQAAAQAAAQICAQIBAQEBAgEBAQEBAQEBAQEBAQEBAAAAAAAAAAAAAAAAAAAAAAAAAQEAAQIBAQIBAQMCAAAAAAAAAAAAAAAAAAAAAAAAAgUDAQIBG0s1RsiJQbl+QryAQrt/RMKEO6RxAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBAkGAAAALXhTPKhzOJxqPadzFDAiAAAAAAAAIFE4Pal0NpZnO6NwJV9CAAAAAAAAFjcnPal0OJ1rOaFuOZtqBQgGFTQlMYleLHtVLX5WLX9XLXlTBwwJAAEAAQMCAAAAHUozMYddLHxVLX5WLX5WL4BYDBgRAAAAHEs1RsiJQbl+QryAQrt/RMKEO6RxAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBAkGAAAANJNkR82MQr6BSMyLFzgnAAAAAAAANZFjR82LQ7+CR8uKOqNwAgQDAAAAGUEtSM6MQ7+CRMWFQ7yACBAMBxEMQrh+R8yLRsaHRcWGStOQIFQ6AAAAAAEBBg0JQLJ6R8yLRseHRcWGStOQM4xgAQMCAAAAG0o0RsiJQbl+QryAQrt/RMKEO6RxAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBAkGAAAAM41gRMSGQLd8RcOFFzYmAAAACRQOQLJ6Qr2AQbl+Qbp/QruBDiEXAAAAGT8sRcWHQbh9QryAQLN6CxcQAAAAG0cxRsaHQLZ8Qbh9Qr+CPKdyBgoIAAAAIVY7R8mIQLZ8Qbl+Qbp+Qrp/DBwUAAAAAAAAG0o0RsiJQbl+QryAQrt/RMKEO6RxAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBAkGAAAAM45hRcaHQLh9RsWGFzgnAAAAFz0qRsaHQbp+QryAQbl+R8mJHk02AAAAGD8sRseIQbl+Qr6BQbR7CRQOAAEAAgMCOJZnRcWFQbp/Qbl+R8qKHUs0AQAAPKZyRMKEQrt/Qbl+RsmJKXBNAAAAAgUEAAAAG0o0RsiJQbl+QryAQrt/RMKEO6RxAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBAkGAAAAM45hRcaHQbh9RcSGFjYmAAAAKnBNRsmJQbl+QryAQbl+RsiILn1WAAAAFz0qRsaHQbl+Qr6BQbR7CRMOAAAAAAAAEy8hRcOFQbp/Qrp/RMWGNpZmGkAtRcaHQbp/QruAQr6BQbV8CRQOAAEBAgQDAAAAG0o0RsiJQbl+QryAQrt/RMKEO6RxAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBAkGAAAAM45hRcaHQbh9RsSGFDIjAAAAOZ9tRMOFQbp/Qr2BQrt/RMGEPKdyAAAAFTknRseHQbl+Qr6BQbR7CRMOAAAAAQMCAAAAL31XRsiIQbl+QryAQrp/P7B4Qr2BQryAQbl+R8qJJF9CAAAAAQMCAQMCAAAAG0o0RsiJQbl+QryAQrt/RMKEO6RxAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBAkGAAAAM45hRcaHQbh9RsaHEiwfCRMORL6CQryAQr2AQbV8Qrp/QryARcGECxkREjAhRseIQbl+Qr6BQbR7CRMOAAAAAQMCAAEADBoTQrp/Qr6BQrt/QryAQ76BQryAQrt/Q8GDPqt2BgwJAAEBAAEBAQMCAAAAG0o0RsiJQbl+QryAQrt/RMKEO6RxAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBAkGAAAAM45hRcWHQbh+RsaHDyMZGUIuR8uKQLd9RcWGK3BNOqVyQr+CR8uKG0gxESoeRsiJQbl+Qr6BQbR7CRMOAAAAAAEBAQICAAAAI19CRsaHQbp+QryAQrt/QryAQbl+RsiJH1A3AAAAAQMCAAAAAQMCAAAAG0o0RsiJQbl+QryAQrt/RMKEO6RxAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBAkGAAAAM45hRcWHQbh+RsWHECUZLHVQR8qJQLh9RsWHEiseL4RbRcWGRsiILHdSESseRceIQbp+Qr6BQbR7CRMOAAAAAAEBAQIBAQIBDB0UQ76CQryAQryAQryAQrt/RMGEO6RxAgMCAAEBAAAAAAAAAQMCAAAAG0o0RsiJQbl+QryAQrt/RMKEO6RxAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBAkGAAAAM45hRcWHQbl+RMGEFjcmOZ9tRMKEQ72BQLV8AwQDIls/R8mJQ8CCOZ9tGD0qRMOFQbp/Qr6BQbR7CRMOAAAAAAEBAQIBAAAAK3RQRseIQbl+QryAQrt/QruAQryAQ7yAESsdAAAAAQIBAAAAAQMCAAAAG0o0RsiJQbl+QryAQrt/RMKEO6RxAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBAkGAAAAM45hRcWGQbt/Qbl+Ilk9Qbl+Qrt/RMWGNpRmAAAAEzEiRcOFQryAQbd9JF5BQruAQryAQr6BQbR7CRMOAAAAAQMCAAAAECQZRMCDQryAQryAQruAQ8KEQryAQbl+RceHNpRlAQEBAQIBAAAAAQMCAAAAG0o0RsiJQbl+QryAQrt/RMKEO6RxAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBAkGAAAAM45hRcWGQryAQLV7M4leQ8CDQbh9R8mJJmlJAAAABw0JPqx2Q7+CQ76CNIxgQLZ8Qr2AQr6BQbR7CRMOAAAAAQMCAAAAM4ZdRceHQbl+Qrt/Q7+CNpFkQLh+Qr2BQbl+RsiJHEcxAAAAAQMCAQMCAAAAG0kzRcWHQLd8Qbp+Qbl9Q8CCOqJwAgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRseHQbh9Qrt/Qrp+Q8CCPKhyBAkGAAAAM45hRcaHQbp/Qbp/QbZ8Qr2BQbl+RseIGD0rAAAAAAAAMIRcRseHQbp/Qbd9Qbp/QryAQr6BQbR7CRMOAAAAAAAAFTQkRsSHQbp/Qrt/Q7+CQLN7ChMONpZnRcWGQbl+Q8GDPqp1BgsJAAEBAQQDAAAAHE43SdOQRMOFRcaHRcWGR82LPq13AgQDAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHUcxSM6MQr6BQ8GDQ8CCRMaHPa52BAkGAAAAM41gRcWGQbl+QruAQryAQrp/QryAQbd+ChgRAAAAAAAAIFQ7R8iJQbh9QryAQrt/Qrp/Qr2AQbN6ChQOAAAAAgEBN5ZnRMOFQbl+Qbh9RsmIKnBNAAAAHU01RsiIQbh9Qbh9RsiJJWNFAAAAAgUDAAAAFTYmNJJlMIdcMYleMYhdMo1gLHhTAgMCAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQMCAAAAGj0rQa95PKJwPaVxPaRxPql0OJRnBAgGAAAANJFjRsuKQr6CQ8CDQ8CDQ7+CRsiIOZ5tAQEBAQIBAAAAECYaRcOFQ8CCQ8CDQ8CDQ7+DQ8OEQrh+CxcQAAAAHEszSM2LQr2BQ8CDQ8KDRL6CDR0UAAEBBQoHPal0RcaGQ76CQ8GDQ7+CDiAXAAAAAQIBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgIBAwUEAwUEAwUEAwUEAwUEAwQDAAEBAAAAMIBYQbN6PqlzPqt0P6t0PqhzQ7Z8KmtKAQEAAgQCAQEABAYEN5VnP653PahzPal0Pal0Pat1PKNwCBEMBAYEOZVmQLB4PqlzPqhzQrR7LHJPAAAAAgQDAAAAIVU7QrV8PKdyPKdyQbV7LHFPAQAAAQIBAAEAAQIBAQIBAQIBAQIBAQIBAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgUEAAQEAAQEAAQEAAQEAAQEAAQEAAAAAAAAAAAAAAAAAgEABggFBgoHBAgGBAgGBAgGBAgGBAgGAQAAAQICAAYGAAMDAAQEAAQEAAUFAQEBAAEAAAAAAAEAAQAABQkGBAgGBAgGBAcGBQsIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAEAAAEAAAEAAAEAAAAAAAAAAAAABwQCGRIIFxEHGBEHGBEHGBEHFxEHGBIIGRMJFRAHBgUCAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAABAMCGBAHFxEIGBEHGBEIFxAHAgEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgIAAAAAlXQw6bZH2apD3KxE3KxE3KxE3KxE3KxE3KtE2alCyZw9p4I0bVUjJBsNAAAAAAAAAgIBAAEAAwMBAAAAd1wm67dI2alD3KxE2apD6bdIYUwfAAAAAwMBAAAAAAAAAAEBAAEAAAEAAAEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgEAAAAAsYk2871H5LJD57RE57RE57RE57RE57RE57RE6LRF7LdG8bxH9b9J47BFkHEtFhIIAAAAAgIBAwMBAAAAknIt+MBI5LFD57RE47FD+cFKe18lAAAABAMBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEAAwMBAwIBAwMBAwMBAwMBAwIBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAQIBAQIBAQIBAQIBAQIBAQIBAgEAAAAAq4Q18LpH4a9D5LFE5LFE5LJE4rBD4a9D4a9D4a9D47BD4rBD4a9D5bJE9r9J06RBMygRAAAABgQCAAAAjG0s9L1I4a5D5LFE4K5D9b5JdlskAAAABAMBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgEAAAAArIU18btH4rBD5bJE5bJE5LFE7rlG871I9b5J871I6LRF4rBD5bJE5bJE4K5C7rlG3q1EJx4NAQEAAAAAjW4s9b5I4q9D5bJE4a9D9r9Jd1wkAAAABAMBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEAAAAAIRoLVUEaTjwYTz0ZTz0YUj8ZRDUWAgEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAABg0JDiQZDSEXDSIYDSEXDiMYDR8WAwIBAAAArIU18btH4rBD5bJE47BD7rpHoHwyUUAabFQim3gw26tC8btI47BD5bJE5bJE4K5D8rxItYw4BQQCAAAAjm4s9b5I4q9D5bJE4a9D9r9JdlskAwIBBwUCAwMBBAMBAwIBAQEAAAAAAAAAAAAABAMBAAAAZU4g/8lO77pH871J8btI+sNL0aJABAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEYxSMmKQruAQ72BQ7yBRMKFPqp1BQgGAAAArIY18btH4rBD5bJE4q9D9L5KTz0ZAAAAAAAAAAAAHRYKpIA08LtH4rBD5bJE5bJE4a9D871JTDoZAAAAkHAt9b5J4q9D5bJE4a9D9r9JfF8mAAAAAAAAAAAAAAAAAAAAAAAAAwIBAAAAAAAABAMBAAAAXkke8rtI3q1C4rBD4K9D6bZFxJc7BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBQgGAAAArIY18btH4rBD5bJE4q9D9L5JWEQbAwMBBgYCAwMBAAAABAMDvpQ77blG47BD5bJE4q9D871InHkwAAAAkHAs9b5J4q9D5bJE5LFE6bVF1KVAn3swmXcviWoralIiOi0TBgQCAAAAAQEBAAAABAMBAAAAX0oe9b5J4a9D5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBQgGAAAArIY18btH4rBD5bJE4q9D9L5JVkMbAAAAAwMBAAAABQQCAAAAV0Qc9L5J4q9D5bJE47FE7bhGx5s9AAAAjG0r9b5J4q9D5bJE5bJE5LFE6bVF871I871I9L5J9b5J7blHyJw9YEofAAAAAQEABQQBAAAAX0oe9b5J4a9D5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBQgGAAAArIY18btH4rBD5bJE4q9D9L5JVkMbAAAAAwMBAAAAAgEBAQEAKiAO57RF5bJE5bJE5LFE6bVF2qlCAwICiWoq9r9J4q9D5bJE5bJE5bJE47FE361C365C4a9D4a9D47BD67dG+cJLkXEuAgECBQQCAAAAX0oe9b5J4a9D5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBQgGAAAArIY18btH4rBD5bJE4q9D9L5JVkMbAAAAAwMBAAAAAgEAAAAAHRcJ361D57NE5LJE5LFE6LRE361ECwcFiGkq9r9J4q9D5bJE5bJE5LFE6bVF8rxI8LpH5bJE5LFE5bJE47BD4K5C+8NLZU0hAAAAAAAAX0oe9b5J4a9D5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBQgGAAAArIY18btH4rBD5bJE4q9D9L5JVkMbAAAAAwMBAAAAAgEBAAAAJBwM5LFF5rJE5bJE5LFE6LRF3KtDBgQDiWoq9r9J4q9D5bJE5LFE6bVF0aJAo38zs4s35bJF6rZF5LFE5bJE47BE67dGyJw9CQcEAAAAX0oe9b5J4a9D5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBQgGAAAArIY18btH4rBD5bJE4q9D9L5JVkMbAAAAAwMBAAAABAMBAgEASDcX8rxJ4rBD5bJE5LFE67dGzqA/AAAAi2wr9b9J4q9D5bJE4a9D9b5JYEsfAAAAAAAAMicR06RB6bVF5LFE5bJE5bJE57RGLiMQAAAAYUse9b5J4a9D5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBQgGAAAArIY18btH4rBD5bJE4q9D9L5JWEQbAgIBBQUCBAMBAwIBAAAAoHwy8rxI4rBD5bJE4rBD8btIrYc1AAAAj28s9b5J4q9D5bJE4q9D9L5JWkYdAwIBCQcDAAAAhGcq9r9J4a9D5bJE47BD77pIRTYXAAAAYkwf9b5J4a9D5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBQgGAAAArIY18btH4rBD5bJE4q9D9b5JTz0ZAAAAAAAAAAAAAAAAcFYk7rlH5LFD5bJE5bJE4a5D9r9JbVQiAAAAkXAt9b5J4q9D5bJE4q9D9L5JVkMcAAAAAgEAAAAAknEu9L1I4q9D5bJE47BD8LtITDoYAAAAYkwf9b5J4a9D5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBQgGAAAArIY18btH4rBD5bJE4rBD8bxHhmgqKB8NPC8UZU4gs4s38btI5bJE5bJE5bJE47FE6LRF26pDGhMJAAAAj28s9b5J4q9D5bJE4q9D871IdFklCAYDFRAIXkgf4q9E5rNE5LJE5bJE47FD67dHOSsTAAAAYUse9b5J4a9D5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBQgGAAAArIY18btH4rBD5bJE5bJE5bJE6rZG57NF7bhH9b5J8LpH47BD5bJE5bJE47FE4a9D+cFLYEofAAAAAAAAjW4s9b5I4q9D5bJE5bJE5rNE4rBEy54+2KdB8bxI57RE5LJE5bJE47BE6bVF0qNADwsFAAAAYEoe9b5J4a9D5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBQgGAAAArIY18btH4rBD5bJE5bJE5bJE5LFE5bJE47FD4a9D4rBD5LFE47BD4a9D6bVF98BKfmIoAAAABgQCAAAAjW4s9b5I4q9D5bJE5bJE5bJE5rNE67dG6LVF4rBD5LFE5LFE4a9D4q9D/MRLaVIhAAAAAAAAX0oe9b5J4a9D5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBQgGAAAAq4U17bhG361C4a9D4q9D4q9D4a9D4a9D4a9D4rBD5LFD6LRF8LtH9b9J1KVBWkYeAAAAAgIBBAMBAAAAi20r8rtH361C4q9D4q9D4q9D4a9D4K5D4a9D4rBD5bJE6rVF871I8rxJg2UpAQEBBQQCAAAAX0oe9b5J4a9D5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBggGAAAAr4k3/8dM8btI9b5J9L5J9L5J9L5J9L5J9L5J8rxI67dG2alCsIk3Z1AhEg4HAAAAAgIBAAAAAwMBAAAAlnUv/8lN77pI871J9b5J9b5J9L5J9b5J9L1J8btI6LRG0aNAnXoxPjAVAAAAAQEABAMBAAAAX0oe9b5J4a9D5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKlzBQkHAQEBLiUSWkceVUMcWkYdXkoeYEwfYEseYEseWUYcSzoYMygSFRAIAAAAAAAAAAAAAwIBAAAAAgEBAwMBAgEBNCgRWEQbUD4ZVkMbXEcdYUseYkwfYEseV0McRzYYLyMQEA0HAAAAAAAABAMBAgIBBgQCAgEBYEse9b5J4a9D5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8GDPKhzAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgEAAwMBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWkYc9r5J4a9D5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQrt/Q8CDPax1DyMZDB0UDiAVECAWECAWECAWECIXDhkRBAMBBAMBAwMBAwIBAgIBAQEAAAAAAAAAAAAAAAAAAQEBIhoNKR8OJx0OKR8OKyAPKiAPKyAPKyAPKyAPKyAPKyAPKyAPKiAPKR8PKB4OJx4OJx4OJx4OJx4OKiAPJR0Odlsm8rxI4q9D5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQryAQryAQryAQ7uAQ7uAQ7uAQ7uAQ7uAQrl+RsWHNItfAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAwIBxZk+7rlI5LFG5rJG5rNG5rJG5rNG5rJG5rNG5rNG5rJG5rNG5rJG5rNG5rJG5rNG5rNG5rNG5rNG5rJG5bJG5rJF5bJE5bJE5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQryAQryAQryAQryAQr2AQryAQr2AQryAQbt+RceHM4xfAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAwIBxJg87bhG47FE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQryAQryAQryAQryAQryAQryAQryAQryAQbp+RcaHM4xfAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAwIBxJg87bhG47FE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEUwRsiIQbl+QryAQryAQryAQryAQryAQryAQryAQryAQryAQbp+RcaHM4xfAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAwIBxJg87bhG47FE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE5bJE47FE7LhGxpk8BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHEQvRcWGQLZ8Qbl+Qbl+Qbl+Qbl+Qbl+Qbl+Qbl+Qbl+Qbl+QLd8RMOFMopdAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAwIBwZY76bVF365D4a9D4a9D4a9D4a9D4a9D4a9D4a9D4a9D4a9D4a9D4a9D4a9D4a9D4a9D4a9D4a9D4a9D4a9D4a9D4a9D4a9D4a9D365D6LVFw5c7BAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQMCAAAAHkozS9aSRsaHR8qJR8qJR8qJR8qJR8qJR8qJR8qJR8qJR8qJRseHStSRNpZmAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAwIB0qNA/sVL875J9b9J9b9J9b9J9b9J9b9J9b9J9b9J9b9J9b9J9b9J9b9J9b9J9b9J9b9J9b9J9b9J9b9J9b9J9b9J9b9J9b9J9b9J875J/cVL1KRABAMBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQIBAAAAESYbKW5LJmVGJmdHJmdHJmdHJmdHJmdHJmdHJmdHJmdHJmdHJmZGKG1LH001AQAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgEBaVEifmEneF0meV4meV4meV4meV4meV4meV4meV4meV4meV4meV4meV4meV4meV4meV4meV4meV4meV4meV4meV4meV4meV4meV4meF0mfWEnaVEiAwIBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQMCAQMCAQMCAQMCAQMCAQMCAQMCAQMCAQMCAQMCAQMCAQMCAQMCAQIBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwIBBAMBAwMBBAMBAwMBAwMBAwMBAwMBAwMBAwMBAwMBAwMBAwMBAwMBAwMBAwMBAwMBAwMBAwMBBAMBAwMBBAMBAwMBBAMBAwMBAwMBBAMBAwIBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

$logoSmallBytes  = [System.Convert]::FromBase64String($logoSmallB64)
$logoSmallStream = New-Object System.IO.MemoryStream(,$logoSmallBytes)
$logoSmall       = [System.Drawing.Bitmap]::FromStream($logoSmallStream)

$logoIconBytes  = [System.Convert]::FromBase64String($logoIconB64)
$logoIconStream = New-Object System.IO.MemoryStream(,$logoIconBytes)
$logoIconBmp    = [System.Drawing.Bitmap]::FromStream($logoIconStream)
$logoIcon       = [System.Drawing.Icon]::FromHandle($logoIconBmp.GetHicon())

#region -- Colores y fuentes
$colorBg        = [System.Drawing.Color]::FromArgb(245, 247, 250)
$colorPanel     = [System.Drawing.Color]::FromArgb(255, 255, 255)
$colorBlue      = [System.Drawing.Color]::FromArgb(24, 95, 165)
$colorBlueDark  = [System.Drawing.Color]::FromArgb(12, 68, 124)
$colorBorder    = [System.Drawing.Color]::FromArgb(220, 225, 235)
$colorMuted     = [System.Drawing.Color]::FromArgb(120, 130, 145)
$colorFooter    = [System.Drawing.Color]::FromArgb(140, 150, 165)
$colorGreen     = [System.Drawing.Color]::FromArgb(29, 158, 117)
$colorRed       = [System.Drawing.Color]::FromArgb(180, 40, 40)
$colorConsole   = [System.Drawing.Color]::FromArgb(13, 17, 23)
$colorOK        = [System.Drawing.Color]::FromArgb(63, 185, 80)
$colorInfo      = [System.Drawing.Color]::FromArgb(121, 192, 255)
$colorWarn      = [System.Drawing.Color]::FromArgb(227, 179, 65)
$colorStep      = [System.Drawing.Color]::FromArgb(139, 148, 158)

$fontLabel  = New-Object System.Drawing.Font("Segoe UI", 8,  [System.Drawing.FontStyle]::Regular)
$fontInput  = New-Object System.Drawing.Font("Segoe UI", 9,  [System.Drawing.FontStyle]::Regular)
$fontBtn    = New-Object System.Drawing.Font("Segoe UI", 9,  [System.Drawing.FontStyle]::Regular)
$fontFooter = New-Object System.Drawing.Font("Segoe UI", 8,  [System.Drawing.FontStyle]::Regular)
$fontTitle  = New-Object System.Drawing.Font("Segoe UI", 11, [System.Drawing.FontStyle]::Regular)
$fontSub    = New-Object System.Drawing.Font("Segoe UI",  7, [System.Drawing.FontStyle]::Regular)
$fontMono   = New-Object System.Drawing.Font("Consolas",  9, [System.Drawing.FontStyle]::Regular)
$fontStep   = New-Object System.Drawing.Font("Segoe UI",  8, [System.Drawing.FontStyle]::Regular)
#endregion

#region -- Formulario principal (mas ancho para consola)
$form = New-Object System.Windows.Forms.Form
$form.Text            = "IntuneDocKit"
$form.Size            = New-Object System.Drawing.Size(900, 660)
$form.StartPosition   = "CenterScreen"
$form.BackColor       = $colorBg
$form.FormBorderStyle = "FixedSingle"
$form.MaximizeBox     = $false
$form.Icon            = $logoIcon
#endregion

#region -- Header
$pnlHeader = New-Object System.Windows.Forms.Panel
$pnlHeader.Size      = New-Object System.Drawing.Size(900, 58)
$pnlHeader.Location  = New-Object System.Drawing.Point(0, 0)
$pnlHeader.BackColor = $colorBlue

$picLogo = New-Object System.Windows.Forms.PictureBox
$picLogo.Image    = $logoSmall
$picLogo.SizeMode = "StretchImage"
$picLogo.Location = New-Object System.Drawing.Point(12, 11)
$picLogo.Size     = New-Object System.Drawing.Size(36, 36)
$picLogo.BackColor = [System.Drawing.Color]::Transparent

$lblTitle = New-Object System.Windows.Forms.Label
$lblTitle.Text      = "IntuneDocKit"
$lblTitle.Font      = $fontTitle
$lblTitle.ForeColor = [System.Drawing.Color]::White
$lblTitle.Location  = New-Object System.Drawing.Point(56, 12)
$lblTitle.Size      = New-Object System.Drawing.Size(200, 20)
$lblTitle.BackColor = [System.Drawing.Color]::Transparent

$lblSub = New-Object System.Windows.Forms.Label
$lblSub.Text      = "Generador de documentacion de Microsoft Intune"
$lblSub.Font      = $fontSub
$lblSub.ForeColor = [System.Drawing.Color]::FromArgb(200, 220, 245)
$lblSub.Location  = New-Object System.Drawing.Point(56, 34)
$lblSub.Size      = New-Object System.Drawing.Size(300, 14)
$lblSub.BackColor = [System.Drawing.Color]::Transparent

$lblVer = New-Object System.Windows.Forms.Label
$lblVer.Text      = "v1.0"
$lblVer.Font      = $fontSub
$lblVer.ForeColor = [System.Drawing.Color]::FromArgb(180, 210, 240)
$lblVer.Location  = New-Object System.Drawing.Point(858, 22)
$lblVer.Size      = New-Object System.Drawing.Size(30, 14)
$lblVer.BackColor = [System.Drawing.Color]::Transparent

$pnlHeader.Controls.AddRange(@($picLogo, $lblTitle, $lblSub, $lblVer))
#endregion

#region -- Panel izquierdo (campos)
$pnlLeft = New-Object System.Windows.Forms.Panel
$pnlLeft.Size        = New-Object System.Drawing.Size(310, 560)
$pnlLeft.Location    = New-Object System.Drawing.Point(10, 68)
$pnlLeft.BackColor   = $colorPanel
$pnlLeft.BorderStyle = "FixedSingle"

$lbl1 = New-Object System.Windows.Forms.Label
$lbl1.Text = "Nombre del cliente"
$lbl1.Font = $fontLabel; $lbl1.ForeColor = $colorMuted
$lbl1.Location = New-Object System.Drawing.Point(14, 14)
$lbl1.Size = New-Object System.Drawing.Size(180, 14)

$txtClient = New-Object System.Windows.Forms.TextBox
$txtClient.Font = $fontInput
$txtClient.Location = New-Object System.Drawing.Point(14, 30)
$txtClient.Size = New-Object System.Drawing.Size(278, 22)
$txtClient.BorderStyle = "FixedSingle"

$lbl2 = New-Object System.Windows.Forms.Label
$lbl2.Text = "Tenant ID"
$lbl2.Font = $fontLabel; $lbl2.ForeColor = $colorMuted
$lbl2.Location = New-Object System.Drawing.Point(14, 62)
$lbl2.Size = New-Object System.Drawing.Size(180, 14)

$txtTenant = New-Object System.Windows.Forms.TextBox
$txtTenant.Font = $fontInput
$txtTenant.Location = New-Object System.Drawing.Point(14, 78)
$txtTenant.Size = New-Object System.Drawing.Size(278, 22)
$txtTenant.BorderStyle = "FixedSingle"

$lbl4 = New-Object System.Windows.Forms.Label
$lbl4.Text = "Usuario (UPN)"
$lbl4.Font = $fontLabel; $lbl4.ForeColor = $colorMuted
$lbl4.Location = New-Object System.Drawing.Point(14, 110)
$lbl4.Size = New-Object System.Drawing.Size(180, 14)

$txtUPN = New-Object System.Windows.Forms.TextBox
$txtUPN.Font = $fontInput
$txtUPN.Location = New-Object System.Drawing.Point(14, 126)
$txtUPN.Size = New-Object System.Drawing.Size(278, 22)
$txtUPN.BorderStyle = "FixedSingle"
$txtUPN.Text = ""

$lbl3 = New-Object System.Windows.Forms.Label
$lbl3.Text = "Modo de ejecucion"
$lbl3.Font = $fontLabel; $lbl3.ForeColor = $colorMuted
$lbl3.Location = New-Object System.Drawing.Point(14, 158)
$lbl3.Size = New-Object System.Drawing.Size(180, 14)

$cmbModo = New-Object System.Windows.Forms.ComboBox
$cmbModo.Font = $fontInput
$cmbModo.Location = New-Object System.Drawing.Point(14, 174)
$cmbModo.Size = New-Object System.Drawing.Size(278, 22)
$cmbModo.DropDownStyle = "DropDownList"
[void]$cmbModo.Items.AddRange(@(
    "Usar App Registration existente",
    "Crear App Registration nueva 1era vez",
    "Solo crear App Registration"
))
$cmbModo.SelectedIndex = 0

# Deshabilitar "Nombre del cliente" en modos 2 y 3 (solo crean App Registration)
$cmbModo.Add_SelectedIndexChanged({
    $soloAppReg = ($cmbModo.SelectedIndex -eq 1 -or $cmbModo.SelectedIndex -eq 2)

    $txtClient.Enabled   = -not $soloAppReg
    $txtClient.BackColor = if ($soloAppReg) { [System.Drawing.Color]::FromArgb(235, 237, 240) } `
                           else             { [System.Drawing.Color]::White }
    $lbl1.ForeColor      = if ($soloAppReg) { [System.Drawing.Color]::FromArgb(180, 185, 195) } `
                           else             { $colorMuted }
    if ($soloAppReg) { $txtClient.Text = "" }
})

$sep1 = New-Object System.Windows.Forms.Panel
$sep1.BackColor = $colorBorder
$sep1.Location = New-Object System.Drawing.Point(14, 212)
$sep1.Size = New-Object System.Drawing.Size(278, 1)

# Barra de progreso por pasos
$lblSteps = New-Object System.Windows.Forms.Label
$lblSteps.Text = "Progreso"
$lblSteps.Font = $fontLabel; $lblSteps.ForeColor = $colorMuted
$lblSteps.Location = New-Object System.Drawing.Point(14, 220)
$lblSteps.Size = New-Object System.Drawing.Size(180, 14)

$prgBar = New-Object System.Windows.Forms.ProgressBar
$prgBar.Location = New-Object System.Drawing.Point(14, 236)
$prgBar.Size = New-Object System.Drawing.Size(278, 12)
$prgBar.Minimum = 0
$prgBar.Maximum = 5
$prgBar.Value = 0

# Labels de pasos
$stepNames = @("Modulos","App Reg","Permisos","XML","Export")
$stepLabels = @()
for ($i = 0; $i -lt 5; $i++) {
    $sl = New-Object System.Windows.Forms.Label
    $sl.Text = $stepNames[$i]
    $sl.Font = $fontStep
    $sl.ForeColor = $colorMuted
    $sl.Location = New-Object System.Drawing.Point((14 + $i * 54), 250)
    $sl.Size = New-Object System.Drawing.Size(54, 14)
    $sl.TextAlign = "MiddleCenter"
    $stepLabels += $sl
    $pnlLeft.Controls.Add($sl)
}

$sep2 = New-Object System.Windows.Forms.Panel
$sep2.BackColor = $colorBorder
$sep2.Location = New-Object System.Drawing.Point(14, 272)
$sep2.Size = New-Object System.Drawing.Size(278, 1)

$btnExport = New-Object System.Windows.Forms.Button
$btnExport.Text = "Exportar"
$btnExport.Font = New-Object System.Drawing.Font("Segoe UI", 9, [System.Drawing.FontStyle]::Regular)
$btnExport.Location = New-Object System.Drawing.Point(14, 282)
$btnExport.Size = New-Object System.Drawing.Size(134, 36)
$btnExport.BackColor = $colorBlue
$btnExport.ForeColor = [System.Drawing.Color]::White
$btnExport.FlatStyle = "Flat"
$btnExport.FlatAppearance.BorderSize = 0
$btnExport.Cursor = "Hand"
$btnExport.TextAlign = "MiddleCenter"

$btnCmd = New-Object System.Windows.Forms.Button
$btnCmd.Text = "Copiar PS"
$btnCmd.Font = $fontBtn
$btnCmd.Location = New-Object System.Drawing.Point(158, 282)
$btnCmd.Size = New-Object System.Drawing.Size(134, 36)
$btnCmd.BackColor = $colorPanel
$btnCmd.ForeColor = $colorBlue
$btnCmd.FlatStyle = "Flat"
$btnCmd.FlatAppearance.BorderColor = $colorBlue
$btnCmd.FlatAppearance.BorderSize = 1
$btnCmd.Cursor = "Hand"

$btnClear = New-Object System.Windows.Forms.Button
$btnClear.Text = "Limpiar consola"
$btnClear.Font = $fontBtn
$btnClear.Location = New-Object System.Drawing.Point(14, 326)
$btnClear.Size = New-Object System.Drawing.Size(278, 28)
$btnClear.BackColor = $colorPanel
$btnClear.ForeColor = $colorMuted
$btnClear.FlatStyle = "Flat"
$btnClear.FlatAppearance.BorderColor = $colorBorder
$btnClear.FlatAppearance.BorderSize = 1
$btnClear.Cursor = "Hand"

$sep3 = New-Object System.Windows.Forms.Panel
$sep3.BackColor = $colorBorder
$sep3.Location = New-Object System.Drawing.Point(14, 362)
$sep3.Size = New-Object System.Drawing.Size(278, 1)

# Caja Device Code (oculta al inicio)
$pnlDeviceCode = New-Object System.Windows.Forms.Panel
$pnlDeviceCode.Location = New-Object System.Drawing.Point(0, 405)
$pnlDeviceCode.Size = New-Object System.Drawing.Size(563, 100)
$pnlDeviceCode.BackColor = [System.Drawing.Color]::FromArgb(12, 45, 74)
$pnlDeviceCode.BorderStyle = "FixedSingle"
$pnlDeviceCode.Visible = $false

$lblDCTitle = New-Object System.Windows.Forms.Label
$lblDCTitle.Text = "Escribe aqui el codigo que aparece en la ventana PowerShell:"
$lblDCTitle.Font = New-Object System.Drawing.Font("Segoe UI", 7, [System.Drawing.FontStyle]::Regular)
$lblDCTitle.ForeColor = [System.Drawing.Color]::FromArgb(139, 148, 158)
$lblDCTitle.Location = New-Object System.Drawing.Point(6, 6)
$lblDCTitle.Size = New-Object System.Drawing.Size(450, 18)

$lblDCCode = New-Object System.Windows.Forms.Label
$lblDCCode.Text = ""
$lblDCCode.Font = New-Object System.Drawing.Font("Consolas", 16, [System.Drawing.FontStyle]::Bold)
$lblDCCode.ForeColor = [System.Drawing.Color]::FromArgb(121, 192, 255)
$lblDCCode.Location = New-Object System.Drawing.Point(6, 22)
$lblDCCode.Size = New-Object System.Drawing.Size(450, 50)

$btnCopyCode = New-Object System.Windows.Forms.Button
$btnCopyCode.Text = "Copiar"
$btnCopyCode.Font = $fontStep
$btnCopyCode.Location = New-Object System.Drawing.Point(6, 66)
$btnCopyCode.Size = New-Object System.Drawing.Size(90, 24)
$btnCopyCode.BackColor = [System.Drawing.Color]::Transparent
$btnCopyCode.ForeColor = [System.Drawing.Color]::FromArgb(121, 192, 255)
$btnCopyCode.FlatStyle = "Flat"
$btnCopyCode.FlatAppearance.BorderColor = [System.Drawing.Color]::FromArgb(24, 95, 165)
$btnCopyCode.FlatAppearance.BorderSize = 1
$btnCopyCode.Cursor = "Hand"

$btnOpenBrowser = New-Object System.Windows.Forms.Button
$btnOpenBrowser.Text = "Abrir web"
$btnOpenBrowser.Font = $fontStep
$btnOpenBrowser.Location = New-Object System.Drawing.Point(104, 66)
$btnOpenBrowser.Size = New-Object System.Drawing.Size(120, 24)
$btnOpenBrowser.BackColor = [System.Drawing.Color]::Transparent
$btnOpenBrowser.ForeColor = [System.Drawing.Color]::FromArgb(121, 192, 255)
$btnOpenBrowser.FlatStyle = "Flat"
$btnOpenBrowser.FlatAppearance.BorderColor = [System.Drawing.Color]::FromArgb(24, 95, 165)
$btnOpenBrowser.FlatAppearance.BorderSize = 1
$btnOpenBrowser.Cursor = "Hand"


# TextBox para ingresar el codigo manualmente
$txtDCInput = New-Object System.Windows.Forms.TextBox
$txtDCInput.Font = New-Object System.Drawing.Font("Consolas", 16, [System.Drawing.FontStyle]::Bold)
$txtDCInput.Location = New-Object System.Drawing.Point(6, 22)
$txtDCInput.Size = New-Object System.Drawing.Size(330, 36)
$txtDCInput.BackColor = [System.Drawing.Color]::FromArgb(20, 60, 100)
$txtDCInput.ForeColor = [System.Drawing.Color]::FromArgb(121, 192, 255)
$txtDCInput.BorderStyle = "FixedSingle"
$txtDCInput.Text = ""

$btnUsarCodigo = New-Object System.Windows.Forms.Button
$btnUsarCodigo.Text = "Usar"
$btnUsarCodigo.Font = $fontBtn
$btnUsarCodigo.Location = New-Object System.Drawing.Point(342, 22)
$btnUsarCodigo.Size = New-Object System.Drawing.Size(60, 36)
$btnUsarCodigo.BackColor = [System.Drawing.Color]::FromArgb(24, 95, 165)
$btnUsarCodigo.ForeColor = [System.Drawing.Color]::White
$btnUsarCodigo.FlatStyle = "Flat"
$btnUsarCodigo.FlatAppearance.BorderSize = 0
$btnUsarCodigo.Cursor = "Hand"

$pnlDeviceCode.Controls.AddRange(@($lblDCTitle, $txtDCInput, $btnUsarCodigo, $btnCopyCode, $btnOpenBrowser))

# Panel confirmacion Y/N (oculto al inicio)
$pnlConfirm = New-Object System.Windows.Forms.Panel
$pnlConfirm.Location = New-Object System.Drawing.Point(0, 405)
$pnlConfirm.Size = New-Object System.Drawing.Size(563, 148)
$pnlConfirm.BackColor = [System.Drawing.Color]::FromArgb(26, 42, 26)
$pnlConfirm.BorderStyle = "FixedSingle"
$pnlConfirm.Visible = $false

$lblConfirmText = New-Object System.Windows.Forms.Label
$lblConfirmText.Text = "Conectar al tenant? Confirme para continuar."
$lblConfirmText.Font = $fontStep
$lblConfirmText.ForeColor = [System.Drawing.Color]::FromArgb(63, 185, 80)
$lblConfirmText.Location = New-Object System.Drawing.Point(6, 4)
$lblConfirmText.Size = New-Object System.Drawing.Size(540, 40)
$lblConfirmText.Font = New-Object System.Drawing.Font("Segoe UI", 10, [System.Drawing.FontStyle]::Regular)
$btnSi = New-Object System.Windows.Forms.Button
$btnSi.Text = "Si (Y)"
$btnSi.Font = New-Object System.Drawing.Font("Segoe UI", 10, [System.Drawing.FontStyle]::Regular)
$btnSi.Location = New-Object System.Drawing.Point(10, 55)
$btnSi.Size = New-Object System.Drawing.Size(100, 36)
$btnSi.BackColor = [System.Drawing.Color]::FromArgb(59, 109, 17)
$btnSi.ForeColor = [System.Drawing.Color]::White
$btnSi.FlatStyle = "Flat"
$btnSi.FlatAppearance.BorderSize = 0
$btnSi.Cursor = "Hand"

$btnNo = New-Object System.Windows.Forms.Button
$btnNo.Text = "No (N)"
$btnNo.Font = New-Object System.Drawing.Font("Segoe UI", 10, [System.Drawing.FontStyle]::Regular)
$btnNo.Location = New-Object System.Drawing.Point(120, 55)
$btnNo.Size = New-Object System.Drawing.Size(100, 36)
$btnNo.BackColor = [System.Drawing.Color]::Transparent
$btnNo.ForeColor = [System.Drawing.Color]::FromArgb(139, 148, 158)
$btnNo.FlatStyle = "Flat"
$btnNo.FlatAppearance.BorderColor = [System.Drawing.Color]::FromArgb(68, 68, 68)
$btnNo.FlatAppearance.BorderSize = 1
$btnNo.Cursor = "Hand"

$pnlConfirm.Controls.AddRange(@($lblConfirmText, $btnSi, $btnNo))

$pnlLeft.Controls.AddRange(@(
    $lbl1, $txtClient,
    $lbl2, $txtTenant,
    $lbl4, $txtUPN,
    $lbl3, $cmbModo,
    $sep1, $lblSteps, $prgBar,
    $sep2, $btnExport, $btnCmd, $btnClear,
    $sep3
))
#endregion

#region -- Panel derecho (consola integrada)
$pnlRight = New-Object System.Windows.Forms.Panel
$pnlRight.Size        = New-Object System.Drawing.Size(565, 560)
$pnlRight.Location    = New-Object System.Drawing.Point(324, 68)
$pnlRight.BackColor   = $colorConsole
$pnlRight.BorderStyle = "FixedSingle"

$lblConsoleTitle = New-Object System.Windows.Forms.Label
$lblConsoleTitle.Text      = "  Consola integrada"
$lblConsoleTitle.Font      = $fontLabel
$lblConsoleTitle.ForeColor = [System.Drawing.Color]::FromArgb(139, 148, 158)
$lblConsoleTitle.BackColor = [System.Drawing.Color]::FromArgb(22, 27, 34)
$lblConsoleTitle.Location  = New-Object System.Drawing.Point(0, 0)
$lblConsoleTitle.Size      = New-Object System.Drawing.Size(563, 20)

$rtbConsole = New-Object System.Windows.Forms.RichTextBox
$rtbConsole.Location    = New-Object System.Drawing.Point(0, 20)
$rtbConsole.Size        = New-Object System.Drawing.Size(563, 395)
$rtbConsole.BackColor   = $colorConsole
$rtbConsole.ForeColor   = [System.Drawing.Color]::FromArgb(230, 237, 243)
$rtbConsole.Font        = $fontMono
$rtbConsole.ReadOnly    = $true
$rtbConsole.BorderStyle = "None"
$rtbConsole.ScrollBars  = "Vertical"
$rtbConsole.WordWrap    = $true

$pnlRight.Controls.AddRange(@($lblConsoleTitle, $rtbConsole, $pnlDeviceCode, $pnlConfirm))
#endregion

#region -- Footer
$pnlFooter = New-Object System.Windows.Forms.Panel
$pnlFooter.Size      = New-Object System.Drawing.Size(900, 28)
$pnlFooter.Location  = New-Object System.Drawing.Point(0, 630)
$pnlFooter.BackColor = [System.Drawing.Color]::FromArgb(230, 233, 238)

$lblFootL = New-Object System.Windows.Forms.Label
$lblFootL.Text = "IntuneDocKit v1.0"
$lblFootL.Font = $fontFooter; $lblFootL.ForeColor = $colorFooter
$lblFootL.Location = New-Object System.Drawing.Point(14, 6)
$lblFootL.Size = New-Object System.Drawing.Size(130, 14)

$lblFootR = New-Object System.Windows.Forms.Label
$lblFootR.Text = "by DeploymentMX  |  2026"
$lblFootR.Font = $fontFooter; $lblFootR.ForeColor = $colorFooter
$lblFootR.Location = New-Object System.Drawing.Point(720, 6)
$lblFootR.Size = New-Object System.Drawing.Size(160, 14)
$lblFootR.TextAlign = "MiddleRight"

$pnlFooter.Controls.AddRange(@($lblFootL, $lblFootR))
#endregion

#region -- Helpers de consola
# Semaforo para sincronizar la confirmacion Y/N
$script:confirmPending = $false
$script:deviceCodeValue = ""

function Write-Console {
    param([string]$Text, [string]$Type = "white")
    $color = switch ($Type) {
        "ok"   { $colorOK }
        "info" { $colorInfo }
        "warn" { $colorWarn }
        "step" { $colorStep }
        "red"  { $colorRed }
        default { [System.Drawing.Color]::FromArgb(230, 237, 243) }
    }
    $rtbConsole.Invoke([Action]{
        $rtbConsole.SelectionStart = $rtbConsole.TextLength
        $rtbConsole.SelectionLength = 0
        $rtbConsole.SelectionColor = $color
        $rtbConsole.AppendText($Text + "`n")
        $rtbConsole.ScrollToCaret()
    })
}

function Update-Step {
    param([int]$Step)
    $prgBar.Invoke([Action]{
        $prgBar.Value = $Step
        for ($i = 0; $i -lt 5; $i++) {
            if ($i -lt $Step) {
                $stepLabels[$i].ForeColor = $colorOK
            } elseif ($i -eq $Step) {
                $stepLabels[$i].ForeColor = $colorInfo
            } else {
                $stepLabels[$i].ForeColor = $colorMuted
            }
        }
    })
}

function Show-DeviceCode {
    param([string]$Code)
    # Panel desactivado - ventana PS es visible durante auth
}

function Hide-DeviceCode {
    # Panel desactivado
}

function Show-Confirm {
    param([string]$Msg)
    $pnlConfirm.Invoke([Action]{
        $lblConfirmText.Text = $Msg
        $pnlConfirm.Visible = $true
    })
}

function Hide-Confirm {
    $pnlConfirm.Invoke([Action]{ $pnlConfirm.Visible = $false })
}
#endregion

#region -- Eventos botones Device Code / Confirm
$btnUsarCodigo.Add_Click({
    $codigo = $txtDCInput.Text.Trim().ToUpper()
    if ($codigo.Length -ge 6) {
        [System.Windows.Forms.Clipboard]::SetText($codigo)
        try { [System.IO.File]::WriteAllText($script:dcodeF, "CODE:$codigo", [System.Text.Encoding]::UTF8) } catch {}
        $script:deviceCodeValue = $codigo
        $lblDCCode.Text = $codigo
        Write-Console "  Codigo ingresado: $codigo - copiado al portapapeles." "ok"
        Write-Console "  Pega el codigo en el browser y autenticate." "warn"
    }
})

$btnCopyCode.Add_Click({
    $c = if ($script:deviceCodeValue -and $script:deviceCodeValue -notmatch "WAITING|AUTHDONE") { $script:deviceCodeValue } else { $txtDCInput.Text.Trim() }
    if ($c) { [System.Windows.Forms.Clipboard]::SetText($c); Write-Console "  Codigo copiado: $c" "ok" }
})

$btnOpenBrowser.Add_Click({
    Start-Process "https://microsoft.com/devicelogin"
    Write-Console "  [OK] Abriendo browser en microsoft.com/devicelogin" "ok"
})

$btnSi.Add_Click({
    Hide-Confirm
    $script:confirmPending = $false
    try { [System.IO.File]::WriteAllText($script:confirmF, "YES", [System.Text.Encoding]::UTF8) } catch {}
    Write-Console "  [OK] Confirmado (Y)" "ok"
})

$btnNo.Add_Click({
    Hide-Confirm
    $script:confirmPending = $false
    try { [System.IO.File]::WriteAllText($script:confirmF, "NO", [System.Text.Encoding]::UTF8) } catch {}
    Write-Console "  [X]  Cancelado (N)" "red"
})

$btnClear.Add_Click({
    $rtbConsole.Clear()
    $prgBar.Value = 0
    $pnlDeviceCode.Visible = $false
    $pnlConfirm.Visible = $false
    for ($i = 0; $i -lt 5; $i++) { $stepLabels[$i].ForeColor = $colorMuted }
})
#endregion

#region -- Evento Copiar Comando PS
$btnCmd.Add_Click({
    $client = $txtClient.Text.Trim()
    $tenant = $txtTenant.Text.Trim()
    $modo   = $cmbModo.SelectedIndex

    if ([string]::IsNullOrEmpty($client)) { $client = "NombreCliente" }
    if ([string]::IsNullOrEmpty($tenant)) { $tenant = "TU-TENANT-ID" }

    $modeFlag = switch ($modo) {
        1       { "" }
        2       { "-OnlyCreateApp" }
        default { "-SkipAppCreation" }
    }

    $masterScript = Join-Path $ScriptRoot "MasterExport-MEM.ps1"
    $cmd = "powershell.exe -ExecutionPolicy Bypass -File `"$masterScript`" -TenantId `"$tenant`" -ClientName `"$client`" $modeFlag"
    [System.Windows.Forms.Clipboard]::SetText($cmd)
    Write-Console "  Comando copiado al portapapeles." "ok"
})
#endregion

#region -- Evento principal Exportar


$btnExport.Add_MouseEnter({ $btnExport.BackColor = $colorBlueDark })
$btnExport.Add_MouseLeave({ $btnExport.BackColor = $colorBlue })

$btnExport.Add_Click({
    $client = $txtClient.Text.Trim()
    $tenant = $txtTenant.Text.Trim()
    $upn    = $txtUPN.Text.Trim()
    $modo   = $cmbModo.SelectedIndex

    if ([string]::IsNullOrEmpty($tenant)) {
        Write-Console "  [X]  Completa el Tenant ID." "red"; return
    }
    if ($modo -eq 0 -and [string]::IsNullOrEmpty($client)) {
        Write-Console "  [X]  Completa el Nombre del Cliente." "red"; return
    }
    if (($modo -eq 1 -or $modo -eq 2) -and [string]::IsNullOrEmpty($client)) { $client = "AppRegistration" }
    $masterScript = Join-Path $ScriptRoot "MasterExport-MEM.ps1"
    if (-not (Test-Path $masterScript)) {
        Write-Console "  [X]  No se encontro MasterExport-MEM.ps1 en: $ScriptRoot" "red"; return
    }
    $modeFlag = switch ($modo) {
        1 { "" }
        2 { "-OnlyCreateApp" }
        default { "-SkipAppCreation" }
    }

    $rtbConsole.Clear()
    $prgBar.Value = 0
    for ($i=0; $i -lt 5; $i++) { $stepLabels[$i].ForeColor = $colorMuted }
    $pnlDeviceCode.Visible = $false
    $pnlConfirm.Visible    = $false

    $script:logF     = [System.IO.Path]::Combine($env:TEMP, "IDK_log.tmp")
    $script:confirmF = [System.IO.Path]::Combine($env:TEMP, "IDK_confirm.tmp")
    $script:dcodeF   = [System.IO.Path]::Combine($env:TEMP, "IDK_dcode.tmp")

    [System.IO.File]::WriteAllText($script:logF,     "", [System.Text.Encoding]::UTF8)
    [System.IO.File]::WriteAllText($script:confirmF, "", [System.Text.Encoding]::UTF8)
    [System.IO.File]::WriteAllText($script:dcodeF,   "", [System.Text.Encoding]::UTF8)

    Write-Console "=================================================" "step"
    Write-Console "  IntuneDocKit -- Iniciando exportacion"           "info"
    Write-Console "  Cliente : $client"                               "white"
    Write-Console "  Tenant  : $tenant"                               "white"
    if ($upn) { Write-Console "  Usuario : $upn"                      "white" }
    Write-Console "=================================================" "step"
    Update-Step 0

    if ($script:activeJob) {
        Stop-Job  $script:activeJob -ErrorAction SilentlyContinue
        Remove-Job $script:activeJob -ErrorAction SilentlyContinue
    }

    $script:activeJob = Start-Job -ArgumentList $script:logF,$script:confirmF,$script:dcodeF,$masterScript,$tenant,$client,$modeFlag,$upn -ScriptBlock {
        param($logF,$confirmF,$dcodeF,$masterSc,$tenantId,$clientNm,$modeFlg,$scriptUpn)

        function wl {
            param([string]$m, [string]$t = 'white')
            [System.IO.File]::AppendAllText($logF, "$t|$m`n", [System.Text.Encoding]::UTF8)
        }

        function Process-Line {
            param([string]$line, $stdin)
            if ($null -eq $line -or $line.Trim() -eq "") { return }
            if    ($line -match '\[OK\]')                { wl $line 'ok'   }
            elseif($line -match '={3,}|PASO \d')         { wl $line 'step' }
            elseif($line -match '\[!\]')                 { wl $line 'warn' }
            elseif($line -match '\[X\]|Error')           { wl $line 'red'  }
            elseif($line -match 'Y/N') {
                wl $line 'warn'
                [System.IO.File]::WriteAllText($confirmF, "PENDING:Conectar al tenant. Continuar?", [System.Text.Encoding]::UTF8)
                $w = 0
                while ([System.IO.File]::ReadAllText($confirmF) -like "PENDING*") {
                    Start-Sleep -Milliseconds 400; $w += 400
                    if ($w -gt 180000) { break }
                }
                $ans = [System.IO.File]::ReadAllText($confirmF).Trim()
                if ($ans -eq "YES") {
                    wl "Respondiendo Y - esperando Device Code..." "ok"
                    $stdin.WriteLine("Y")
                    # Escribir WAITING para que la GUI abra el browser
                    [System.IO.File]::WriteAllText($dcodeF, "WAITING", [System.Text.Encoding]::UTF8)
                } else { wl "Respondiendo N" "warn"; $stdin.WriteLine("N") }
            }
            elseif($line -match 'enter the code|devicelogin|To sign in') {
                wl $line 'warn'
                if ($line -match 'enter the code ([A-Z0-9]{6,9})') {
                    [System.IO.File]::WriteAllText($dcodeF, "CODE:$($matches[1])", [System.Text.Encoding]::UTF8)
                }
            }
            elseif($line -match 'user principal name|Please specify your user') {
                wl $line 'warn'; $stdin.WriteLine($scriptUpn)
            }
            elseif($line -match 'Client name for|Nombre del cliente') {
                $stdin.WriteLine($clientNm)
            }
            elseif($line -match 'does not exist|Create it\? \(Y/N\)') {
                wl $line 'warn'; $stdin.WriteLine("Y")
            }
            elseif($line -match 'Export path \(e\.g') {
                $stdin.WriteLine("")
            }
            elseif($line -match '^Windows PowerShell|^Copyright.*Microsoft|^Install the latest|^https://aka') {
                # ignorar banner
            }
            elseif($line -match 'microsoft.com|login.microsoft|devicelogin') {
                    wl $line 'warn'
                    if ($line -match '([A-Z0-9]{8,9})') {
                        [System.IO.File]::WriteAllText($dcodeF, "CODE:$($matches[1])", [System.Text.Encoding]::UTF8)
                    }
                }
                else { 
                    # Log todo para debug - ver que manda MSAL
                    wl $line 'white' 
                }
        }

        function Run-Proc {
            param([string]$exe, [string]$argStr)

            $psi = New-Object System.Diagnostics.ProcessStartInfo
            $psi.FileName               = $exe
            $psi.Arguments              = $argStr
            $psi.UseShellExecute        = $false
            $psi.RedirectStandardOutput = $true
            $psi.RedirectStandardError  = $true
            $psi.RedirectStandardInput  = $true
             $psi.CreateNoWindow         = $true
             $psi.WindowStyle            = [System.Diagnostics.ProcessWindowStyle]::Hidden
            if ($scriptUpn) { $psi.EnvironmentVariables["INTUMEDOCKIT_UPN"] = $scriptUpn }
            $psi.EnvironmentVariables["INTUMEDOCKIT_GUI"] = "1"

            $proc = [System.Diagnostics.Process]::Start($psi)
            wl "[OK] PID=$($proc.Id)" "ok"

            # Leer stdout linea por linea (el Job corre en background, no bloquea la GUI)
            while (-not $proc.StandardOutput.EndOfStream) {
                $line = $proc.StandardOutput.ReadLine()
                if ($null -ne $line) { Process-Line $line $proc.StandardInput }
            }
            $proc.WaitForExit()
            $errTxt = $proc.StandardError.ReadToEnd()
            if ($errTxt -and $errTxt.Trim()) { wl $errTxt 'red' }
            wl "Exit=$($proc.ExitCode)" "step"
        }

        wl "=== Job iniciado ===" "step"

        if (-not (Test-Path $masterSc)) {
            wl "[X] No se encontro: $masterSc" "red"
            wl "===DONE===" "ok"; return
        }


        try {
            $argStr = "-NoProfile -ExecutionPolicy Bypass -File `"$masterSc`" -TenantId `"$tenantId`" -ClientName `"$clientNm`""
            if ($modeFlg -and $modeFlg.Trim() -ne "") { $argStr += " $modeFlg" }

            if ($modeFlg -like "*SkipAppCreation*") {
                # Modo exportar existente: oculto con captura
                wl "=== Iniciando exportacion ===" "step"
                Run-Proc "powershell.exe" $argStr
            } else {
                # Modo crear App Registration: ventana visible (necesita WAM/browser)
                wl "=== Iniciando creacion de App Registration ===" "step"
                wl "Se abrira una ventana de PowerShell para autenticacion." "warn"
                wl "Completa el proceso en esa ventana." "warn"
                $proc = Start-Process "powershell.exe" -ArgumentList $argStr -PassThru -Wait
                wl "Proceso App Registration finalizado. Exit=$($proc.ExitCode)" "step"
            }
        } catch {
            wl "[X] $($_.Exception.Message)" "red"
        }

        wl "===DONE===" "ok"
    }

    Write-Console "  Job ID: $($script:activeJob.Id)" "step"

    $script:lastLogPos      = 0
    $script:confirmPending  = $false
    $script:deviceCodeValue = ""

    if ($script:exportTimer) { $script:exportTimer.Stop() }
    $script:exportTimer = New-Object System.Windows.Forms.Timer
    $script:exportTimer.Interval = 400

    $script:exportTimer.Add_Tick({
        try {
            $txt = [System.IO.File]::ReadAllText($script:logF, [System.Text.Encoding]::UTF8)
            $allLines = $txt -split "`n" | Where-Object { $_.Trim() -ne "" }
            if ($allLines.Count -gt $script:lastLogPos) {
                $newLines = $allLines[$script:lastLogPos..($allLines.Count - 1)]
                foreach ($line in $newLines) {
                    $parts = $line -split "\|", 2
                    if ($parts.Count -ge 2) { $ltype = $parts[0].Trim() } else { $ltype = "white" }
                    if ($parts.Count -ge 2) { $lmsg = $parts[1].TrimEnd("`r") } else { $lmsg = $line }
                    Write-Console $lmsg $ltype
                    if ($lmsg -match "PASO 1")                              { Update-Step 0 }
                    if ($lmsg -match "PASO 2")                              { Update-Step 1 }
                    if ($lmsg -match "PASO 3")                              { Update-Step 2 }
                    if ($lmsg -match "PASO 4")                              { Update-Step 3 }
                    if ($lmsg -match "PASO 5|Exportando|Iniciando exportac") { Update-Step 4 }
                    if ($lmsg -match "COMPLETADO|Document saved|AUTHDONE")  { Update-Step 5 }
                    if ($lmsg -match "===DONE===") {
                        $script:exportTimer.Stop()
                        Update-Step 5
                        Hide-DeviceCode; Hide-Confirm
                        Write-Console "" "white"
                        Write-Console "  Proceso finalizado correctamente." "ok"
                    }
                }
                $script:lastLogPos = $allLines.Count
            }
        } catch {}

        try {
            $dc = [System.IO.File]::ReadAllText($script:dcodeF, [System.Text.Encoding]::UTF8).Trim()
            if ($dc -eq "WAITING" -and $script:deviceCodeValue -ne "WAITING") {
                $script:deviceCodeValue = "WAITING"
                Start-Process "https://microsoft.com/devicelogin"
                Write-Console "  Abriendo browser en microsoft.com/devicelogin..." "warn"
                Write-Console "  El codigo aparecera en la ventana de PowerShell de la barra de tareas." "warn"
                Write-Console "  Ingresalo en el browser y autenticate con tu cuenta de Intune." "warn"
                # Panel desactivado
                # Monitorear transcript para obtener el codigo real
                $script:transcriptF = [System.IO.Path]::Combine($env:TEMP, "IDK_transcript.tmp")
            } elseif ($dc -eq "AUTHDONE" -and $script:deviceCodeValue -ne "AUTHDONE") {
                $script:deviceCodeValue = "AUTHDONE"
                Hide-DeviceCode
                Write-Console "  Autenticacion completada correctamente." "ok"
            } elseif ($dc -match "^CODE:(.+)$") {
                $code = $matches[1]
                if ($code -ne $script:deviceCodeValue) {
                    $script:deviceCodeValue = $code
                    # Device code panel desactivado - ventana PS es visible
                }
            }
            # Monitorear transcript para codigo real de MSAL
            if ($script:transcriptF -and (Test-Path $script:transcriptF) -and $script:deviceCodeValue -eq "WAITING") {
                try {
                    $tc = [System.IO.File]::ReadAllText($script:transcriptF, [System.Text.Encoding]::UTF8)
                    if ($tc -match "enter the code ([A-Z0-9]{6,9})" -or $tc -match "code ([A-Z0-9]{8,9}) to auth") {
                        $realCode = $matches[1]
                        $script:deviceCodeValue = $realCode
                        # Panel desactivado
                        [System.IO.File]::WriteAllText($script:dcodeF, "CODE:$realCode", [System.Text.Encoding]::UTF8)
                    }
                } catch {}
            }
        } catch {}

        if (-not $script:confirmPending) {
            try {
                $cf = [System.IO.File]::ReadAllText($script:confirmF, [System.Text.Encoding]::UTF8)
                if ($cf -match "^PENDING:(.+)") {
                    $script:confirmPending = $true
                    Show-Confirm $matches[1].TrimEnd("`r`n")
                }
            } catch {}
        }

        $jState = $script:activeJob.State
        if ($jState -eq "Completed" -or $jState -eq "Failed" -or $jState -eq "Stopped") {
            $script:exportTimer.Stop()
            Hide-DeviceCode; Hide-Confirm
            if ($jState -eq "Failed") {
                try { $r = $script:activeJob.ChildJobs[0].JobStateInfo.Reason.Message; Write-Console "  [X] $r" "red" } catch {}
                try { $o = Receive-Job $script:activeJob 2>&1 | Out-String; if($o.Trim()){Write-Console $o "red"} } catch {}
            }
            if ($rtbConsole.Text -notmatch "Proceso finalizado") {
                Write-Console "" "white"
                Write-Console "  Proceso finalizado." "ok"
            }
        }
    })

    $script:exportTimer.Start()
})

$form.Controls.AddRange(@($pnlHeader, $pnlLeft, $pnlRight, $pnlFooter))
$form.Add_Shown({ $form.Activate() })
[void]$form.ShowDialog()
